# Generated by Django 5.0.1 on 2024-02-13 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingDate', models.DateField()),
                ('eventTitle', models.CharField(max_length=150)),
                ('eventDescription', models.CharField(max_length=250)),
                ('eventLocation', models.ManyToManyField(to='trm.location')),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrenceDate', models.DateField()),
                ('occurrenceDescription', models.CharField(max_length=200)),
                ('occurrenceStatus', models.CharField(max_length=15)),
                ('agent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='trm.agent')),
                ('incidentType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trm.incidenttype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trm.location')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('relevance', models.CharField(max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trm.agent')),
            ],
        ),
    ]
